name = "ghostnaps/jest"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
JestCore = { workspace = "ghostnaps/jest_core", version = "^" }

[dev_dependencies]
JestGlobals = { workspace = "ghostnaps/jest_globals", version = "^" }
