name = "flipbook_labs/jest"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
jest-core = { workspace = "flipbook_labs/jest_core", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
