[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.34.0" }
lune = { source = "lune-org/lune", version = "0.8.9" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.4" }
selene = { source = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.18.1" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.3.2" }
