name = "ghostnaps/jest_workspace"
version = "3.8.0"
description = "A Luau testing framework based on Jest. See JestGlobals for the entry point."
authors = [
    "Raymond Ng <rng@roblox.com>",
    "Daniel Fox <dfox@roblox.com>",
    "Marin Minnerly <me@vocksel.com>",
]
repository = "https://github.com/ghostnaps/jest-luau"
license = "MIT"
workspace_members = ["src/*"]
pesde_version = "0.5.0-rc.16"
private = true

[target]
environment = "lune"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
