name = "ghostnaps/jest_workspace"
version = "3.8.0"
description = "A Luau testing framework based on Jest. See JestGlobals for the entry point."
authors = [
    "Marin Minnerly <me@vocksel.com>",
    "Raymond Ng <rng@roblox.com>",
    "Daniel Fox <dfox@roblox.com>",
]
repository = "https://github.com/ghostnaps/jest-luau"
license = "MIT"
workspace_members = ["src/*", "test-runner"]
pesde_version = "0.5.0-rc.12"
private = true

[target]
environment = "lune"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"
