name = "flipbook_labs/jest_jasmine2"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }

[dev_dependencies]
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
expect = { workspace = "flipbook_labs/expect", version = "^" }
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }
