name = "ghostnaps/diff_sequences"
description = "Compare items in two sequences to find a longest common subsequence."
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
