name = "ghostnaps/jest_mock_rbx"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }

[dev_dependencies]
jest-config = { workspace = "ghostnaps/jest_config", version = "^" }
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
