name = "flipbook_labs/jest_reporters"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
jest-console = { workspace = "flipbook_labs/jest_console", version = "^" }
jest-message-util = { workspace = "flipbook_labs/jest_message_util", version = "^" }
jest-mock = { workspace = "flipbook_labs/jest_mock", version = "^" }
jest-test-result = { workspace = "flipbook_labs/jest_test_result", version = "^" }
jest-types = { workspace = "flipbook_labs/jest_types", version = "^" }
jest-util = { workspace = "flipbook_labs/jest_util", version = "^" }
path = { workspace = "flipbook_labs/path", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }
test-utils = { workspace = "flipbook_labs/test_utils", version = "^" }

[dev_dependencies]
jest-config = { workspace = "flipbook_labs/jest_config", version = "^" }
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
jest-snapshot-serializer-raw = { workspace = "flipbook_labs/jest_snapshot_serializer_raw", version = "^" }
pretty-format = { workspace = "flipbook_labs/pretty_format", version = "^" }
