name = "ghostnaps/jest_config"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
LuauPolyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
Promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
ChalkLua = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
JestEnvironmentLuau = { workspace = "ghostnaps/jest_environment_luau", version = "^" }
JestGetType = { workspace = "ghostnaps/jest_get_type", version = "^" }
JestTypes = { workspace = "ghostnaps/jest_types", version = "^" }
JestUtil = { workspace = "ghostnaps/jest_util", version = "^" }
JestValidate = { workspace = "ghostnaps/jest_validate", version = "^" }
RobloxShared = { workspace = "ghostnaps/roblox_shared", version = "^" }

[dev_dependencies]
JestGlobals = { workspace = "ghostnaps/jest_globals", version = "^" }
JestSnapshotSerializerRaw = { workspace = "ghostnaps/jest_snapshot_serializer_raw", version = "^" }
PrettyFormat = { workspace = "ghostnaps/pretty_format", version = "^" }
