name = "ghostnaps/jest_config"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
jest-environment-luau = { workspace = "ghostnaps/jest_environment_luau", version = "^" }
jest-get-type = { workspace = "ghostnaps/jest_get_type", version = "^" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }
jest-util = { workspace = "ghostnaps/jest_util", version = "^" }
jest-validate = { workspace = "ghostnaps/jest_validate", version = "^" }
roblox-shared = { workspace = "ghostnaps/roblox_shared", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
jest-snapshot-serializer-raw = { workspace = "ghostnaps/jest_snapshot_serializer_raw", version = "^" }
pretty-format = { workspace = "ghostnaps/pretty_format", version = "^" }
