name = "ghostnaps/jest_runtime"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
expect = { workspace = "ghostnaps/expect", version = "^" }
jest-fake-timers = { workspace = "ghostnaps/jest_fake_timers", version = "^" }
jest-mock = { workspace = "ghostnaps/jest_mock", version = "^" }
jest-mock-genv = { workspace = "ghostnaps/jest_mock_genv", version = "^" }
jest-snapshot = { workspace = "ghostnaps/jest_snapshot", version = "^" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }

[dev_dependencies]
jest-config = { workspace = "ghostnaps/jest_config", version = "^" }
jest-environment-luau = { workspace = "ghostnaps/jest_environment_luau", version = "^" }
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
