name = "ghostnaps/jest_get_type"
description = "A utility function to get the type of a value, including Luau and Roblox types."
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
