name = "ghostnaps/jest_get_type"
description = "A utility function to get the type of a value, including Luau and Roblox types."
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
