name = "flipbook_labs/jest_circus"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
jest-get-type = { workspace = "flipbook_labs/jest_get_type", version = "^" }
jest-types = { workspace = "flipbook_labs/jest_types", version = "^" }
jest-util = { workspace = "flipbook_labs/jest_util", version = "^" }
pretty-format = { workspace = "flipbook_labs/pretty_format", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
