name = "ghostnaps/jest_circus"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
jest-get-type = { workspace = "ghostnaps/jest_get_type", version = "^" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }
jest-util = { workspace = "ghostnaps/jest_util", version = "^" }
pretty-format = { workspace = "ghostnaps/pretty_format", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
