name = "flipbook_labs/jest_globals"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
expect = { workspace = "flipbook_labs/expect", version = "^" }
jest-environment = { workspace = "flipbook_labs/jest_environment", version = "^" }
jest-types = { workspace = "flipbook_labs/jest_types", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
