name = "flipbook_labs/pretty_format"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
react-is = { wally = "wally#jsdotlua/react-is", version = "^17.2.0" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
jest-get-type = { workspace = "flipbook_labs/jest_get_type", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }

[dev_dependencies]
react = { wally = "wally#jsdotlua/react", version = "^17.2.0" }
react-test-renderer = { wally = "wally#jsdotlua/react-test-renderer", version = "^17.2.0" }
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
