name = "flipbook_labs/jest_snapshot"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
jest-types = { workspace = "flipbook_labs/jest_types", version = "^" }
jest-diff = { workspace = "flipbook_labs/jest_diff", version = "^" }
jest-get-type = { workspace = "flipbook_labs/jest_get_type", version = "^" }
jest-matcher-utils = { workspace = "flipbook_labs/jest_matcher_utils", version = "^" }
pretty-format = { workspace = "flipbook_labs/pretty_format", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
