name = "flipbook_labs/throat"
version = "0.1.0"
description = "Throttle a collection of promise returning functions."

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
