name = "ghostnaps/throat"
version = "0.1.0"
description = "Throttle a collection of promise returning functions."

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
