name = "ghostnaps/jest_example"
version = "0.1.0"
authors = ["Marin Minnerly <me@vocksel.com>"]
repository = "https://github.com/ghostnaps/jest-luau"
license = "MIT"
pesde_version = "0.5.0-rc.12"
private = true

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dev_dependencies]
jest = { repo = "ghostnaps/jest-luau", rev = "cd578f5", path = "src/jest" }
jest-globals = { repo = "ghostnaps/jest-luau", rev = "cd578f5", path = "src/jest-globals" }
