name = "ghostnaps/jest_example_test_runner"
version = "0.1.0"
authors = ["Marin Minnerly <me@vocksel.com>"]
repository = "https://github.com/ghostnaps/jest-luau"
license = "MIT"
pesde_version = "0.5.0-rc.12"
private = true

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dev_dependencies]
Jest = { workspace = "ghostnaps/jest", version = "^" }
JestGlobals = { workspace = "ghostnaps/jest_globals", version = "^" }
