name = "flipbook_labs/jest_console"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
jest-each = { workspace = "flipbook_labs/jest_each", version = "^" }
jest-message-util = { workspace = "flipbook_labs/jest_message_util", version = "^" }
jest-types = { workspace = "flipbook_labs/jest_types", version = "^" }
jest-util = { workspace = "flipbook_labs/jest_util", version = "^" }
jest-mock = { workspace = "flipbook_labs/jest_mock", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
