name = "ghostnaps/jest_matcher_utils"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
jest-diff = { workspace = "ghostnaps/jest_diff", version = "^" }
jest-get-type = { workspace = "ghostnaps/jest_get_type", version = "^" }
pretty-format = { workspace = "ghostnaps/pretty_format", version = "^" }
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
roblox-shared = { workspace = "ghostnaps/roblox_shared", version = "^" }
test-utils = { workspace = "ghostnaps/test_utils", version = "^" }
