name = "ghostnaps/jest_validate"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
chalk = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
