name = "ghostnaps/jest_runner"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
LuauPolyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
Promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
ChalkLua = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
JestConsole = { workspace = "ghostnaps/jest_console", version = "^" }
JestEnvironment = { workspace = "ghostnaps/jest_environment", version = "^" }
JestMessageUtil = { workspace = "ghostnaps/jest_message_util", version = "^" }
JestTestResult = { workspace = "ghostnaps/jest_test_result", version = "^" }
JestTypes = { workspace = "ghostnaps/jest_types", version = "^" }
JestUtil = { workspace = "ghostnaps/jest_util", version = "^" }
Emittery = { workspace = "ghostnaps/emittery", version = "^" }
JestCircus = { workspace = "ghostnaps/jest_circus", version = "^" }
JestRuntime = { workspace = "ghostnaps/jest_runtime", version = "^" }
Throat = { workspace = "ghostnaps/throat", version = "^" }
RobloxShared = { workspace = "ghostnaps/roblox_shared", version = "^" }

[dev_dependencies]
JestGlobals = { workspace = "ghostnaps/jest_globals", version = "^" }
