name = "flipbook_labs/jest_types"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
