name = "ghostnaps/jest_mock"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
jest-mock-genv = { workspace = "ghostnaps/jest_mock_genv", version = "^" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }

[dev_dependencies]
jest-config = { workspace = "ghostnaps/jest_config", version = "^" }
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
