name = "ghostnaps/jest_message_util"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
chalk-lua = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
jest-types = { workspace = "ghostnaps/jest_types", version = "^" }
pretty-format = { workspace = "ghostnaps/pretty_format", version = "^" }
roblox-shared = { workspace = "ghostnaps/roblox_shared", version = "^" }

jest-get-type = { workspace = "ghostnaps/jest_get_type", version = "^" }
jest-message-util = { workspace = "ghostnaps/jest_message_util", version = "^" }
jest-util = { workspace = "ghostnaps/jest_util", version = "^" }
jest-matcher-utils = { workspace = "ghostnaps/jest_matcher_utils", version = "^" }
jest-snapshot = { workspace = "ghostnaps/jest_snapshot", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
jest-snapshot-serializer-raw = { workspace = "ghostnaps/jest_snapshot_serializer_raw", version = "^" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
