name = "ghostnaps/roblox_shared"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
jest-get-type = { workspace = "ghostnaps/jest_get_type", version = "^" }
jest-mock = { workspace = "ghostnaps/jest_mock", version = "^" }

[dev_dependencies]
jest-config = { workspace = "ghostnaps/jest_config", version = "^" }
jest-globals = { workspace = "ghostnaps/jest_globals", version = "^" }
