name = "flipbook_labs/jest_util"
version = "0.1.0"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
luau-polyfill = { wally = "wally#jsdotlua/luau-polyfill", version = "^1.2.7" }
promise = { wally = "wally#jsdotlua/promise", version = "^3.5.2" }
chalk-lua = { wally = "wally#jsdotlua/chalk", version = "^0.2.1" }
regexp = { wally = "wally#jsdotlua/luau-regexp", version = "^0.2.1" }
picomatch = { wally = "wally#jsdotlua/picomatch", version = "^0.4.0" }
jest_types = { workspace = "flipbook_labs/jest_types", version = "^" }
roblox-shared = { workspace = "flipbook_labs/roblox_shared", version = "^" }

[dev_dependencies]
jest-globals = { workspace = "flipbook_labs/jest_globals", version = "^" }
